name = "Flag Format"
author = "ning"
description = """
Hey uh, I forgot the flag format...
Could you please find it for me?"""
category = "misc"
difficulty = "free points"
points = 15
flag = "saint{FLAG_FORMAT}"
