name = "Very secure censorship"
author = "Alex"
description = """
This flag contains top secret information,
so I decided to pixelate it."""
category = "misc"
difficulty = "medium"
points = 250
flag = "saint{p1x3l_p3rf3ct}"
