name = "Holy church of Jowett Part 2"
author = "Alex"
description = """
I wonder what secrets the pope keeps in the church
"""
category = "web"
difficulty = "hard"
points = 500
flag = "saint{h1_j0w3tt_y0u_r3411y_4r3_th3_b3st}"
