name = "RSA 0"
author = "ning"
description = """
Read: https://en.wikipedia.org/wiki/RSA_(cryptosystem)
It is very cool"""
category = "crypto"
difficulty = "medium"
points = 125
flag = "saint{RSA_1n1t14t10n}"
