name = "Ominous Pole"
author = "Alex"
description = """
Well that's an ominous pole! Why does the DoD need that?
Flag is the Coordinates of the pole, rounded to 4 Decimal Places
(Like saint{-123.45, 67.898})
"""
category = "osint"
difficulty = "medium"
points = 200
flag = "saint{-35.2976, 149.1517}"