name = "Time Machine"
author = "ning"
description = """
Hmm, I added the flag before but deleted it.

Can you use a time machine to get it back?
"""
category = "misc"
difficulty = "medium"
points = 250
flag = "saint{T1m3_m@ch1n3_Act1v@t3d!}"
