name = "Holy church of Jowett Part 1"
author = "Alex"
description = """
Come join the holy church of Jowett, high ranking cardinals get a flag
"""
category = "web"
difficulty = "medium"
points = 250
flag = "saint{v4l1d4t1ng_s3cr3ts_1s_f0r_chumps}"
