name = "Game Shop"
author = "Alex"
description = """
Oh no! My favorite games store moved! Where did it move to?
Flag is the address (number and street name), all lowercase, with underscores for spaces
"""
category = "osint"
difficulty = "easy"
points = 150
flag = "saint{119_barrack_street}"
